#!/usr/bin/env python3
"""
Export AgentNotebook memory to YAML for backup and portability.

This script connects to the metadata database and exports all active
AgentNotebook entries to a YAML file for backup, migration, or review.

Usage:
    python export_memory.py [output_file]
    
Arguments:
    output_file - Output YAML file path (default: memory_dump.yaml)
"""

import sys
import os
from pathlib import Path
from typing import Dict, Any

# Add server directory to path
sys.path.insert(0, os.path.dirname(__file__))

from sqlmodel import Session, select
from models import AgentNotebook, get_engine
from config import load_config


def export_memory_to_yaml(output_file: str = "memory_dump.yaml") -> None:
    """
    Export all active AgentNotebook entries to a YAML file.
    
    The YAML structure organizes entries by domain, then by key:
    
    domains:
      user_prefs:
        theme: "dark"
        language: "en"
      self_correction:
        tool_name_error: "Error details..."
    
    Args:
        output_file: Path to the output YAML file
    """
    # Load configuration
    config = load_config()
    
    # Connect to metadata database
    meta_db_url = config.get('metadata_database', {}).get('url')
    if not meta_db_url:
        # Fall back to legacy single database config
        meta_db_url = config.get('database', {}).get('url', 'sqlite:///chameleon_meta.db')
    
    print(f"Connecting to metadata database: {meta_db_url}")
    engine = get_engine(meta_db_url)
    
    # Query all active AgentNotebook entries
    with Session(engine) as session:
        statement = select(AgentNotebook).where(AgentNotebook.is_active == True)
        entries = session.exec(statement).all()
        
        if not entries:
            print("⚠️  No active AgentNotebook entries found")
            return
        
        print(f"Found {len(entries)} active memory entries")
        
        # Organize entries by domain
        domains: Dict[str, Dict[str, str]] = {}
        for entry in entries:
            if entry.domain not in domains:
                domains[entry.domain] = {}
            domains[entry.domain][entry.key] = entry.value
        
        # Create YAML structure
        yaml_data = {
            'domains': domains
        }
        
        # Export to YAML
        try:
            import yaml
            
            with open(output_file, 'w') as f:
                yaml.dump(yaml_data, f, default_flow_style=False, sort_keys=False)
            
            print(f"✅ Memory exported successfully to: {output_file}")
            print(f"   Domains: {', '.join(domains.keys())}")
            print(f"   Total entries: {len(entries)}")
            
        except ImportError:
            # PyYAML not installed, fall back to JSON-like format
            print("⚠️  PyYAML not installed. Falling back to simple format...")
            
            with open(output_file, 'w') as f:
                f.write("# Agent Notebook Memory Dump\n")
                f.write("# Generated by export_memory.py\n\n")
                f.write("domains:\n")
                
                for domain, entries_dict in domains.items():
                    f.write(f"  {domain}:\n")
                    for key, value in entries_dict.items():
                        # Escape multi-line values
                        if '\n' in value:
                            f.write(f"    {key}: |\n")
                            for line in value.split('\n'):
                                f.write(f"      {line}\n")
                        else:
                            # Escape quotes in value
                            escaped_value = value.replace('"', '\\"')
                            f.write(f'    {key}: "{escaped_value}"\n')
            
            print(f"✅ Memory exported successfully to: {output_file}")
            print(f"   Domains: {', '.join(domains.keys())}")
            print(f"   Total entries: {len(entries)}")


def main():
    """Main entry point for the export script."""
    # Parse command-line arguments
    output_file = sys.argv[1] if len(sys.argv) > 1 else "memory_dump.yaml"
    
    print("=" * 60)
    print("Agent Notebook Memory Export")
    print("=" * 60)
    print()
    
    try:
        export_memory_to_yaml(output_file)
    except Exception as e:
        print(f"❌ Error exporting memory: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    print()
    print("=" * 60)


if __name__ == '__main__':
    main()
